# Autocomplete
[ -r /usr/share/bash-completion/bash_completion   ] && . /usr/share/bash-completion/bash_completion
# Makes my bash name look nice
 if [ "$EUID" -ne 0 ]
 then export PS1="\[$(tput bold)\]\[$(tput setaf 9)\][\[$(tput setaf 11)\]\u\[$(tput setaf 4)\]@\[$(tput setaf 11)\]\h\[$(tput setaf 9)\]] \[$(tput setaf 1)\]\w\[$(tput sgr0)\] \[$(tput setaf 14)\]\$ \[$(tput sgr0)\]"
	 else export PS1="\[$(tput bold)\][ROOT] \W\[$(tput sgr0)\] # "
 fi
stty -ixon # Disables Strg-S and Strg-Q
xset r rate 300 120
setxkbmap -option caps:escape

HISTSIZE=100000

set -o vi
export NICKNAME="Henning"
export EDITOR=nvim
export BROWSER=qutebrowser
shopt -s histappend
shopt -s autocd
shopt -s cdspell
# export FZF_DEFAULT_COMMAND='find ~'
export FZF_DEFAULT_COMMAND='rg --files --hidden --vimgrep -s'
export MYVIMRC="/home/henning/dotfiles/vimrc"
# System managment
alias off="sudo shutdown 0"
alias pq="sudo pacman -Rs $(pacman -Qqdt)"
alias ht="htop -d 3"
alias df="df -h |grep /$"
alias p="sudo pacman"
alias ift="sudo iftop -i wlp3s0"
# Program shortcuts
alias yt="youtube-dl"
alias py="python3.7"
alias z="zathura"
alias tb="thunderbird"
# Vim aliases
alias v="nvim"
alias vim="nvim"
alias sv="sudo nvim"
# Miscelaneous
alias cl="clear"
alias nf="clear; neofetch; echo ''"
alias grep="grep --color=auto"
alias notes="cp ~/Templates/notes.md ./notes.md; v notes.md"
alias article="cp ~/Templates/article.tex ./article_new.tex; v article_new.tex; move article_new.tex"
alias starwars="telnet towel.blinkenlights.nl"
# File managment
alias ls="ls -F --color=auto"
alias la="ls -AhH --color=auto --group-directories-first"
alias lla="ls -alhH --color=auto --group-directories-first"
alias so="sudo du -hcs"
alias soa="sudo du -ahc -d 3 ./ 2>/dev/null | sort -h "
alias lwatch="watch -n .2 ls -lh"
alias frm="rm -rf"
alias trm="latexmk -c &> /dev/null"
alias cd="pushd"
alias cc="popd; clear; echo '$(pwd)'"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias r="ranger"
alias sr="sudo ranger"
# Shortcuts to Schule directories
alias seng="cd ~/Schule/Eng; clear"
alias sbio="cd ~/Schule/Biologie; clear"
alias sche="cd ~/Schule/Chemie; clear"
alias sdeu="cd ~/Schule/Deutsch; clear"
alias sds="cd ~/Schule/DS; clear"
alias sges="cd ~/Schule/Geschichte; clear"
alias sinf="cd ~/Schule/Informatik; clear"
alias smat="cd ~/Schule/Mathe; clear"
alias smuk="cd ~/Schule/MuK; clear"
alias spb="cd ~/Schule/PB; clear"
alias sek="cd ~/Schule/Erdkunde; clear"
alias sspa="cd ~/Schule/Spanisch; clear"
alias tm="tmux -2 -f ~/.tmux.conf"
# Shortcuts to home subdirectories
alias hdow="cd ~/Downloads; clear"
alias hcod="cd ~/Coding; clear"
alias hcon="cd ~/.config; clear"
alias hdoc="cd ~/Documents; clear"
alias hpic="cd ~/Pictures; clear"
alias hsch="cd ~/Schule; clear"
alias hscr="cd ~/scripts; clear"
alias hvim="cd ~/.config/nvim; clear"
alias hdot="cd ~/dotfiles; clear"
# Shortcuts to edit config files
alias rcconf="sudo nvim ~/.config/ranger/rc.conf"
alias conf="nvim ~/dotfiles/i3config"
alias brc="nvim ~/.bashrc"
alias xres="nvim ~/dotfiles/Xresources"
alias xresr="xrdb ~/.Xresources"
alias vrc="nvim ~/dotfiles/vimrc"
alias nvrc="nvim ~/.config/nvim/init.vim"
alias zshrc="nvim ~/.zshrc"
alias pbar="nvim ~/.config/polybar/config"
alias gruvbox="~/scripts/gruvbox ; urxvtc ; exit"
# Git dotfiles version controll
alias dfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
