# Makes my bash name look nice
 if [ "$EUID" -ne 0 ]
 then export PS1="\[$(tput bold)\]\[$(tput setaf 6)\][\[$(tput setaf 3)\]\u\[$(tput setaf 6)\]@\[$(tput setaf 6)\]\h\[$(tput setaf 6)\]]\[$(tput setaf 6)\]{\[$(tput setaf 1)\]\w\[$(tput setaf 7)\]\[$(tput setaf 6)\]} \[$(tput sgr0)\]\n\[$(tput setaf 6)\]\$ \[$(tput sgr0)\]"
	 else export PS1="\[$(tput bold)\]\[$(tput setaf 6)\][\[$(tput setaf 3)\]ROOT\[$(tput setaf 6)\]@\[$(tput setaf 6)\]$(hostname | awk '{print toupper($0)}') \[$(tput setaf 1)\]\w\[$(tput setaf 1)\]]\[$(tput setaf 7)\] \[$(tput sgr0)\]\n# "
 fi

HISTSIZE=100000

set -o vi
export NICKNAME="Henning"
export EDITOR=vim
shopt -s histappend
shopt -s autocd
shopt -s  cdspell
export FZF_DEFAULT_COMMAND='find .'
stty -ixon # Disables Strg-S and Strg-Q
# System
alias ift="sudo iftop -i wlp3s0"
# alias sapt="sudo apt"
# alias saptupd="sudo apt update"
# alias saptupg="sudo apt upgrade"
alias v="vim -u /home/henning/.vimrc"
alias p="sudo pacman"
alias r="ranger"
alias e="emacs -nw"
alias tb="thunderbird"
alias sr="sudo ranger"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias sv="sudo vim"
alias sv="sudo vim"
alias cl="clear"
alias df="df -h |grep /$"
alias ht="htop -d 3"
alias rc="killall compton; compton &"
alias nf="neofetch"
alias pq="sudo pacman -Rs $(pacman -Qqdt)"
alias off="sudo shutdown 0"
alias fbg="nitrogen --set-auto"
alias frm=" rm -rf"
alias grep="grep --color=auto"
alias htop="htop -d 3"
alias email="thunderbird &"
alias lock="i3lock -i /usr/share/backgrounds/campsky.jpg"
alias notes="cp ~/Templates/notes.md ./notes.md; v notes.md"
alias cding="cd ~/Coding/"
alias article="cp ~/Templates/article.tex ./article_new.tex; v article_new.tex"
alias repbar="/home/henning/scripts/repbar.sh"
#alias pb="cd Schule/PB/"
alias starwars="telnet towel.blinkenlights.nl"
alias flux="~/Downloads/xflux"
# ls-command shortcuts
alias ls="ls -F --color=auto"
alias la="ls -ahH --color=auto --group-directories-first"
alias ll='sudo ls -hHn --color=auto --group-directories-first'
alias so="sudo du -hcs"
alias lla="ls -alhH --color=auto --group-directories-first"
alias soa="sudo du -ahc -d 3 ./ 2>/dev/null | sort -h "
alias soar="sudo du -ahc -d 8 / 2>/dev/null | sort -h "
alias lwatch="watch -n .2 ls -lh"
alias lalwatch="watch -n .2 ls -alHnh --color=auto --group-directories-first"
# Shortcuts to edit config files
alias rcconf="sudo vim ~/.config/ranger/rc.conf"
alias conf="vim ~/dotfiles/i3config"
alias sconf="vim /etc/i3status.conf"
alias brc="vim ~/.bashrc"
alias xres="vim ~/dotfiles/Xresources"
alias xresr="xrdb ~/.Xresources"
alias vrc="vim ~/dotfiles/vimrc"
alias vac="vim ~/.vim/src/autoclose.vim"
alias zshrc="vim ~/.zshrc"
alias pbar="vim ~/.config/polybar/config"
alias spbar="polybar default && polybar bottom"
alias termrc="vim ~/.config/termite/config"
alias solarized="/home/henning/scripts/solarized.sh ; urxvtc ; exit"
alias spacegray="/home/henning/scripts/spacegray.sh ; urxvtc ; exit"
alias transparent="/home/henning/scripts/transparent.sh ; urxvtc ; exit"
# Git dotfiles version controll
alias dfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
